# Generated by Django 4.0.2 on 2022-09-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_lastname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Appointment lastname'),
        ),
    ]
