# Generated by Django 4.0.7 on 2022-10-02 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_employee_first_name_employee_patronymic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='random_uuid',
        ),
        migrations.AlterField(
            model_name='queue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
